### ISSUE TITLE
Error running model with default inputs: Cannot open 'landuse'

### ISSUE THREAD

**Issue by Dabwiso** [JudithVerstegen/PLUC_Mozambique#3]
Hi. I am trying to run the model with the default input parameters. I am running this command at the command line `python LU_Moz.py` and I get this error:

```
Traceback (most recent call last):
  File "C:\Users\laptopuser\Documents\PhD_Work\Chapters\Chapter_2\PLUC_Mozambique-1.0.0\model\LU_Moz.py", line 888, in <module>
    myModel = LandUseChangeModel()
  File "C:\Users\laptopuser\Documents\PhD_Work\Chapters\Chapter_2\PLUC_Mozambique-1.0.0\model\LU_Moz.py", line 710, in __init__
    setclone('landuse')
TypeError: Cannot open 'landuse'. Note: only the PCRaster file format is supported as input argument.
```

I am using python 3.5 within a conda env where I installed all the requirements on a Windows machine.
Can somebody help me with that? Thank you

**Comment by nuest** [comment]
Hi @Dabwiso ! Were you able to fix the issue?

**Comment by Dabwiso** [comment]
Hi @nuest, I managed by simply adding the extension to the landuse file name:  setclone('landuse.map')
